#pragma once

#include "Constants.h"

const unsigned char PROGMEM tiles[10][8] =
{
  {0x0d, 0x9f, 0x2d, 0x97, 0x0d, 0x9f, 0x2d, 0x97 },
  {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 },
  {0x40, 0x40, 0x40, 0x40, 0x40, 0x40, 0x40, 0x40 },
  {0x16, 0x05, 0x12, 0x04, 0x14, 0x02, 0x15, 0x06 },
  {0x40, 0x40, 0x4f, 0x09, 0xed, 0x09, 0x4f, 0x40 },
  {0x05, 0x02, 0x05, 0x02, 0x05, 0x02, 0x05, 0x02 },
  {0x07, 0x09, 0x07, 0x0f, 0x07, 0x09, 0x07, 0x0f },
  {0x00, 0x38, 0x44, 0x82, 0x9a, 0xa2, 0x44, 0x38 },
  {0x09, 0x22, 0x09, 0x22, 0x09, 0x22, 0x09, 0x22 },
  {0x82, 0x5a, 0x9a, 0x42, 0x98, 0x5a, 0x9a, 0x58 }
};

const unsigned char PROGMEM level1Map[LEVEL_HEIGHT * LEVEL_WIDTH] = {
//0      1      2      3      4      5      6      7      8      9,     10     11     12     13     14     15     16     17     18     19,    20     21     22     23     24     25     26     27     28     29,    30     31     32     33  
  ROCK2, ROCK2, ROCK2, ROCK2, ROCK2, ROCK2, ROCK2, ROCK2, ROCK2, ROCK2, GATE1, GATE1, GATE1, ROCK2, ROCK2, ROCK2, ROCK2, ROCK2, ROCK2, ROCK2, ROCK2, ROCK2, ROCK2, ROCK2, ROCK2, ROCK2, ROCK2, ROCK2, ROCK2, ROCK2, ROCK2, ROCK2, ROCK2, ROCK2,
  EMPTY, EMPTY, EDGE1, EDGE1, EDGE1, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EDGE1, EDGE1, EDGE1, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
  EMPTY, EMPTY, BRICK, BRICK, BRICK, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EDGE1, EDGE1, SIGN1, EMPTY, EMPTY, EMPTY, BRICK, BRICK, BRICK, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EDGE1, EDGE1, SIGN1, EMPTY, EMPTY, EMPTY,
  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EDGE1, EDGE1, EMPTY, EMPTY, EMPTY, EMPTY, BRICK, BRICK, BRICK, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EDGE1, EDGE1, EMPTY, EMPTY, EMPTY, EMPTY, BRICK, BRICK, BRICK, EMPTY, EMPTY, EMPTY,
  EDGE1, SIGN1, EMPTY, EMPTY, EMPTY, EMPTY, BRICK, BRICK, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EDGE1, SIGN1, EMPTY, EMPTY, EMPTY, EMPTY, BRICK, BRICK, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
  BRICK, BRICK, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, BRICK, BRICK, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
  EMPTY, EMPTY, EMPTY, EMPTY, BRICK, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, ROCK1, ROCK1, ROCK1,
  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
};

const uint8_t PROGMEM level1StartingPositions[10] = {
3, 1,    7, 3,    13, 2,    16, 4,    29, 2, 
};


//-------------------------------------------------------------------------------------


const unsigned char PROGMEM level2Map[LEVEL_HEIGHT * LEVEL_WIDTH] = {
  EMPTY, ROCK1, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, ROCK1, ROCK1, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,  ROCK1, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, ROCK1, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, SIGN1,
  SIGN1, EMPTY, ROCK2, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, ROCK1, ROCK1, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,  ROCK1, ROCK1, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, ROCK1, ROCK1, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
  EMPTY, EMPTY, EMPTY, ROCK1, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, ROCK1, ROCK1, EMPTY, EMPTY, EMPTY, EMPTY,  ROCK1, ROCK1, ROCK1, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, ROCK1, EMPTY, ROCK1, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, SIGN1,
  SIGN1, EMPTY, EMPTY, EMPTY, ROCK2, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, ROCK1, ROCK1, EMPTY, EMPTY, EMPTY,  EMPTY, ROCK1, ROCK1, ROCK1, EMPTY, EMPTY, EMPTY, EMPTY, ROCK1, EMPTY, EMPTY, ROCK1, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, ROCK1, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, ROCK1, ROCK1, EMPTY, EMPTY,  EMPTY, EMPTY, ROCK1, ROCK1, ROCK1, EMPTY, EMPTY, EMPTY, EMPTY, ROCK1, EMPTY, EMPTY, ROCK1, EMPTY, EMPTY, EMPTY, SIGN1,
  SIGN1, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, ROCK2, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, ROCK1, ROCK1, EMPTY,  EMPTY, EMPTY, EMPTY, ROCK1, ROCK1, ROCK1, EMPTY, EMPTY, EMPTY, EMPTY, ROCK1, EMPTY, EMPTY, ROCK1, EMPTY, EMPTY, EMPTY,
  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, ROCK1, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, ROCK1, ROCK1,  EMPTY, EMPTY, EMPTY, EMPTY, ROCK1, ROCK1, ROCK1, EMPTY, EMPTY, EMPTY, EMPTY, ROCK1, EMPTY, EMPTY, ROCK1, EMPTY, SIGN1,
  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,  EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY,
};

const uint8_t PROGMEM level2StartingPositions[8] = {
1, 2,    4, 5,    6, 6,    14,8, 
};


const uint8_t *levelMaps[] =                    { level1Map, level2Map };
const uint8_t *levelStartingPositions[] =      { level1StartingPositions, level2StartingPositions };
const uint8_t levelStartingPositionsCount[] =   { 5, 6 }; // Note half the size of the starting positions array as therse have x, y, coordinates
